const fs = require('fs');
const filePaths = [
    "src/app/modules/internalControl/budgetVarianceReports/materialConsumptionTableData.js",
    "src/app/modules/internalControl/budgetVarianceReports/materialPriceVarianceTable.js",
    "src/app/modules/internalControl/budgetVarianceReports/subGeneralLedgerModalForIncomeStatement.js",
    "src/app/modules/internalControl/costingPricingModel/costConfiguration/costElement/createModal.js",
    "src/app/modules/internalControl/ProjectedFinancialStatement/modals/inventoryTransactionModal.js",
    "src/app/modules/inventoryManagement/configuration/configPlantWarehouse/businessUnitEdit/editForm.js",
    "src/app/modules/inventoryManagement/configuration/configPlantWarehouse/businessUnitView/viewForm.js",
    "src/app/modules/inventoryManagement/configuration/configPlantWarehouse/businessUnitView/viewModal.js",
    "src/app/modules/inventoryManagement/configuration/configPlantWarehouse/common/confirmtionModal.js",
    "src/app/modules/inventoryManagement/configuration/inventoryLocation/businessUnitView/viewForm.js",
    "src/app/modules/inventoryManagement/configuration/inventoryLocation/businessUnitView/viewModal.js",
    "src/app/modules/inventoryManagement/configuration/plant/businessUnitView/viewForm.js",
    "src/app/modules/inventoryManagement/configuration/plant/businessUnitView/viewModal.js",
    "src/app/modules/inventoryManagement/configuration/transportZoneUpdate/Form/utils.js",
    "src/app/modules/inventoryManagement/configuration/warehouse/businessUnitView/viewForm.js",
    "src/app/modules/inventoryManagement/configuration/warehouse/businessUnitView/viewModal.js",
    "src/app/modules/inventoryManagement/configuration/warehouse/common/confirmtionModal.js",
    "src/app/modules/inventoryManagement/configuration/warehouse/common/toastMessage.js",
    "src/app/modules/inventoryManagement/inventoryLoan/landing/index.js",
    "src/app/modules/inventoryManagement/inventoryLoan/landing/salesOrderReportModal.js",
    "src/app/modules/inventoryManagement/reports/inventoryLoanRegister/GeneralLedgerTable.js",
    "src/app/modules/inventoryManagement/reports/inventoryLoanRegister/partnerModal.js",
    "src/app/modules/inventoryManagement/reports/inventoryLoanRegister/subScheduleModal.js",
    "src/app/modules/inventoryManagement/reports/inventoryStatement/helper.js",
    "src/app/modules/inventoryManagement/reports/inventoryStatement/table/detailsModal.js",
    "src/app/modules/inventoryManagement/reports/inventoryStatement/table/pagination.js",
    "src/app/modules/inventoryManagement/reports/inventoryStatement/table/search.js",
    "src/app/modules/inventoryManagement/reports/inventoryStatement/table/table.js",
    "src/app/modules/inventoryManagement/reports/InventoryStatementReport/Table/TableForSummary.js",
    "src/app/modules/inventoryManagement/reports/itemwiseserialdetails/index.js",
    "src/app/modules/inventoryManagement/warehouseManagement/cancelInventory/view/addEditForm.js",
    "src/app/modules/inventoryManagement/warehouseManagement/cancelInventory/view/form.js",
    "src/app/modules/inventoryManagement/warehouseManagement/delivery/salesInvoice/invoice.js",
    "src/app/modules/inventoryManagement/warehouseManagement/delivery/Table/hologram.js",
    "src/app/modules/inventoryManagement/warehouseManagement/grnforPo/view/form.js",
    "src/app/modules/inventoryManagement/warehouseManagement/grnforPo/view/viewPage.js",
    "src/app/modules/inventoryManagement/warehouseManagement/inventoryLoan/landing/index.js",
    "src/app/modules/inventoryManagement/warehouseManagement/inventoryLoan/landing/salesOrderReportModal.js",
    "src/app/modules/inventoryManagement/warehouseManagement/inventoryLoanNew/helper.js",
    "src/app/modules/inventoryManagement/warehouseManagement/invTransaction/View/viewForm.js",
    "src/app/modules/inventoryManagement/warehouseManagement/invTransactionImport/View/viewForm.js",
    "src/app/modules/learningAndDevelopment/assessment/assessmentForm/editForm/addEditFrom.js",
    "src/app/modules/learningAndDevelopment/assessment/assessmentForm/editForm/form.js",
    "src/app/modules/performanceManagement/_chart/IBarChart.js",
    "src/app/modules/performanceManagement/_chart/IPieChart.js",
    "src/app/modules/performanceManagement/_helper/GlobalMaxMin.js",
    "src/app/modules/performanceManagement/_helper/IndividualMin.js",
    "src/app/modules/performanceManagement/_helper/pmsCommonTable/demoData.js",
    "src/app/modules/performanceManagement/_helper/SbuMin.js",
    "src/app/modules/performanceManagement/_helper/upDownArrow.js",
    "src/app/modules/performanceManagement/corporateKpi/achievement/View/viewModal.js",
    "src/app/modules/performanceManagement/corporateKpi/balancedScore/_redux/Actions.js",
    "src/app/modules/performanceManagement/corporateKpi/balancedScore/_redux/Api.js",
    "src/app/modules/performanceManagement/corporateKpi/kpiTargetEntry/Edit/detailsView.js",
    "src/app/modules/performanceManagement/corporateKpi/PerformanceChart/IBarChart.js",
    "src/app/modules/performanceManagement/corporateKpi/PerformanceChart/IPieChart.js",
    "src/app/modules/performanceManagement/corporateKpi/PerformanceChart/ISpeedoMeter.js",
    "src/app/modules/performanceManagement/departmentalKpi/kpiTargetEntry/Edit/detailsView.js",
    "src/app/modules/performanceManagement/departmentalKpi/PerformanceChart/IBarChart.js",
    "src/app/modules/performanceManagement/departmentalKpi/PerformanceChart/IPieChart.js",
    "src/app/modules/performanceManagement/departmentalKpi/PerformanceChart/ISpeedoMeter.js",
    "src/app/modules/performanceManagement/individualKpi/balancedScore/Table/KPIScoreCard.jsx",
    "src/app/modules/performanceManagement/individualKpi/copyKpi/Table/tableHeader.js",
    "src/app/modules/performanceManagement/individualKpi/copyKpi/Table/tableRow.js",
    "src/app/modules/performanceManagement/individualKpi/kpiConfigure/index.js",
    "src/app/modules/performanceManagement/individualKpi/kpiDashboard/grouphChart.js"
];

// Loop through each file path and delete the file
filePaths.forEach((filePath) => {
    fs.unlink(filePath, (err) => {
        if (err) {
            console.error(`Error deleting file ${filePath}:`, err.message);
        } else {
            console.log(`File ${filePath} deleted successfully.`);
        }
    });
});
