
  export const data =    [ {
        sl: 1,
        rowId: 6005,
        partnerRfqid: 162,
        itemId: 23,
        itemCode: 'Code',
        itemName: 'SSD',
        uomId: 2,
        uomName: 'Metric',
        purchaseDescription: 'demo description',
        rfqQty: 4,
        rate: 10,
        value: 2,
        supplierName: 'SAL',
        supplierRefNo: '326',
        supplierRefDate: '2020-09-16T08:45:51.9'
      },
      {
        sl: 2,
        rowId: 204,
        partnerRfqid: 161,
        itemId: 22,
        itemCode: 'Code',
        itemName: 'Matador GL (Akij)',
        uomId: 1,
        uomName: 'KG',
        purchaseDescription: 'demo description',
        rfqQty: 6,
        rate: 20,
        value: 3,
        supplierName: 'Akij Shipment',
        supplierRefNo: '',
        supplierRefDate: '2020-09-16T05:03:46.89'
      },
      {
        sl: 3,
        rowId: 205,
        partnerRfqid: 161,
        itemId: 23,
        itemCode: 'Code',
        itemName: 'SSD',
        uomId: 2,
        uomName: 'Metric',
        purchaseDescription: 'demo description',
        rfqQty: 4,
        rate: 0,
        value: 0,
        supplierName: 'Akij Shipment',
        supplierRefNo: '',
        supplierRefDate: '2020-09-16T05:03:46.89'
      },
      {
        sl: 4,
        rowId: 200,
        partnerRfqid: 160,
        itemId: 23,
        itemCode: 'Code',
        itemName: 'SSD',
        uomId: 2,
        uomName: 'Metric',
        purchaseDescription: 'demo description',
        rfqQty: 4,
        rate: 0,
        value: 0,
        supplierName: 'Akij Rock Ltd',
        supplierRefNo: '',
        supplierRefDate: '2020-09-16T05:03:46.863'
      },
      {
        sl: 5,
        rowId: 201,
        partnerRfqid: 160,
        itemId: 22,
        itemCode: 'Code',
        itemName: 'Matador GL (Akij)',
        uomId: 1,
        uomName: 'KG',
        purchaseDescription: 'demo description',
        rfqQty: 6,
        rate: 0,
        value: 0,
        supplierName: 'Akij Rock Ltd',
        supplierRefNo: '',
        supplierRefDate: '2020-09-16T05:03:46.863'
      }
    ]