export const approveHandeler = ({ item, onApproveHandler, profileData, cb, isApproved, isTransferCreated, journalCode, isUpdateGivenBankInfo, bankPaymentValues, isFundReceived }) => {

    const payload = {

        intFundTransferRequestId: item.intFundTransferRequestId || 0,
        strRequestCode: item.strRequestCode || "",
        intRequestTypeId: item.intRequestTypeId,
        strRequestType: item.strRequestType || "",
        intRequestByUnitId: item.intRequestByUnitId || 0,
        strRequestByUnitName: item.strRequestByUnitName || "",
        intRequestToUnitId: item.intRequestToUnitId || 0,
        strRequestToUnitName: item.strRequestToUnitName || "",
        dteRequestDate: item.dteRequestDate || "",
        numAmount: item.numAmount || 0,
        intRequestedBankId: item.intRequestedBankId || 0,
        strRequestedBankName: item.strRequestedBankName || "",
        intRequestedBankBranchId: item.intRequestedBankBranchId || 0,
        strRequestedBankBranchName: item.strRequestedBankBranchName || "",
        strRequestedBankAccountNumber: item.strRequestedBankAccountNumber || "",
        strRequestedBankAccountName: item.strRequestedBankAccountName || "",
        intRequestedBankAccountId: item.intRequestedBankAccountId || 0,
        strRequestedBankRouting: item.strRequestedBankRouting || "",
        intRequestGLId: item?.intRequestGLId?.generalLedgerId || item?.intRequestGlid || 0,
        strRequestGlName: item?.strRequestGlName?.generalLedgerName || item?.strRequestGlName || "",
        strRequestGlCode: item?.strRequestGlCode?.generalLedgerCode || item?.strRequestGlCode || "",
        intGivenBankId: isUpdateGivenBankInfo ? bankPaymentValues?.bankAcc?.bankId : item.intGivenBankId || 0,
        strGivenBankName: isUpdateGivenBankInfo ? bankPaymentValues?.bankAcc?.bankName : item.strGivenBankName || "",
        intGivenBankBranchId: isUpdateGivenBankInfo ? bankPaymentValues?.bankAcc?.bankBranch_Id : item.intGivenBankBranchId || 0,
        strGivenBankBranchName: isUpdateGivenBankInfo ? bankPaymentValues?.bankAcc?.bankBranchName : item.strGivenBankBranchName || "",
        strGivenBankAccountNumber: isUpdateGivenBankInfo ? bankPaymentValues?.bankAcc?.bankAccNo : item.strGivenBankAccountNumber || "",
        strGivenBankAccountName: isUpdateGivenBankInfo ? bankPaymentValues?.bankAcc?.label : item.strGivenBankAccountName || "",
        strGivenBankAccountId: isUpdateGivenBankInfo ? bankPaymentValues?.bankAcc?.value : item?.strGivenBankAccountId || 0,
        strGivenBankRouting: isUpdateGivenBankInfo ? bankPaymentValues?.bankAcc?.bankRouting : item?.strGivenBankRouting || "",
        intGivenGlid: isUpdateGivenBankInfo ? bankPaymentValues?.bankAcc?.generalLedgerId : item?.intGivenGlid || 0,
        strGivenGlCode: isUpdateGivenBankInfo ? bankPaymentValues?.bankAcc?.generalLedgerCode : item?.strGivenGlCode || "",
        strGivenGlName: isUpdateGivenBankInfo ? bankPaymentValues?.bankAcc?.generalLedgerName : item?.strGivenGlName || "",
        strRemarks: item.strRemarks || "",
        dteExpectedDate: item.dteExpectedDate || "",
        intResponsibleEmpId: item.intResponsibleEmpId || 0,
        strResponsibleEmpName: item.strResponsibleEmpName || "",
        isActive: item.isActive ?? true,
        isApproved: isApproved,
        intApproveBy: profileData?.userId || 0,
        dteApproveDatetime: new Date().toISOString(),
        // intRequestGLId: item?.intRequestGLId || 0,
        // strRequestGlName: item?.strRequestGlName || "",
        strRequestPartnerId: item?.strRequestPartnerId || 0,
        strRequestPartnerName: item?.strRequestPartnerName || "",
        isTransferCreated: isTransferCreated || 0,
        strGivenPartnerName: item?.strGivenPartnerName || "",
        strGivenstrPartnerCode: item?.strGivenstrPartnerCode || "",
        strRequestPartnerCode: item?.strRequestPartnerCode || "",
        intUpdateBy: profileData?.userId,
        strReceivingJournal: isFundReceived ? journalCode : "",
        strSendingJournal: isFundReceived ? item?.strSendingJournal : journalCode || "",
        isFundReceived: isFundReceived || false,
        intGivenPartnerId: item?.intGivenPartnerId || 0
    }

    onApproveHandler(`/fino/FundManagement/CreateOrEditFundTransferRequest`, payload, cb, true);


}