

export const pmsDemoData = [
    {
      bsc: "Finance",
      kpiList: [
        {
          label: "kpi 1",
          target: "2",
          achievement: "3",
          isParent: true,
          numberOfChild: 4,
          parentName: "Obj A",
        },
        {
          label: "kpi 2",
          target: "2",
          achievement: "3",
          isParent: false,
          numberOfChild: 4,
          parentName: "Obj A",
        },
        {
          label: "kpi 3",
          target: "2",
          achievement: "3",
          isParent: false,
          numberOfChild: 4,
          parentName: "Obj A",
        },
        {
          label: "kpi 4",
          target: "2",
          achievement: "3",
          isParent: false,
          numberOfChild: 4,
          parentName: "Obj A",
        },
        {
          label: "kpi 5",
          target: "2",
          achievement: "3",
          isParent: true,
          numberOfChild: 2,
          parentName: "Obj B",
        },
        {
          label: "kpi 6",
          target: "2",
          achievement: "3",
          isParent: false,
          numberOfChild: 2,
          parentName: "Obj B",
        },
        {
          label: "kpi 7",
          target: "2",
          achievement: "3",
          isParent: true,
          numberOfChild: 1,
          parentName: "Obj C",
        },
      ],
    },
    {
      bsc: "Process",
      kpiList: [
        {
          label: "kpi 1",
          target: "2",
          achievement: "3",
          isParent: true,
          numberOfChild: 4,
          parentName: "Obj A",
        },
        {
          label: "kpi 2",
          target: "2",
          achievement: "3",
          isParent: false,
          numberOfChild: 4,
          parentName: "Obj A",
        },
        {
          label: "kpi 3",
          target: "2",
          achievement: "3",
          isParent: false,
          numberOfChild: 4,
          parentName: "Obj A",
        },
        {
          label: "kpi 4",
          target: "2",
          achievement: "3",
          isParent: false,
          numberOfChild: 4,
          parentName: "Obj A",
        },
        {
          label: "kpi 5",
          target: "2",
          achievement: "3",
          isParent: true,
          numberOfChild: 2,
          parentName: "Obj S",
        },
        {
          label: "kpi 6",
          target: "2",
          achievement: "3",
          isParent: false,
          numberOfChild: 2,
          parentName: "Obj S",
        },
      ],
    },
    {
      bsc: "",
      kpiList: [
        {
          label: "",
          target: "2",
          achievement: "3",
          isParent: true,
          numberOfChild: 1,
          parentName: "Total",
        },
      ],
    },
  ];