export const withEncryptedAPI = [
  "/EProcurement/GetPermissionWisePlantDDL",
  "/EProcurement/GetPermissionWiseWarehouseDDL",
  "/EProcurement/GetPurchaseOrganizationDDL",
  "/EProcurement/GetPRReferrenceDDL",
  "/EProcurement/GetBusinessTransactionsAndLedger",
  "/EProcurement/GetBaseCurrencyListDDL",
  "/EProcurement/GetPaymentTermsListDDL",
  "/EProcurement/GetSupplierListDDL",
  "/EProcurement/GetItemsForPRReference",
  "/RequestForQuotation/CreateRequestForQuotation",
  "/RequestForQuotation/EditRequestForQuotation",
  "/RequestForQuotation/GetRequestForQuotationLanding",
  "/RequestForQuotation/GetRequestForQuotationDetails",

  // CS
  "/ComparativeStatement/GetComparativeStatementLanding",
  "/ComparativeStatement/GetSupplierStatementForCS",
  "/ComparativeStatement/GetSupplierWiseCS",
  "ComparativeStatement/GetItemWiseStatementForCS",
  "/ComparativeStatement/GetItemWiseStatementDetails",
  "/ComparativeStatement/CreateAndUpdateSupplierWiseCS",
  "/ComparativeStatement/CreateAndUpdateItemWiseCS",
  "/ComparativeStatement/GetByCostComponentByUnit",
  "/ComparativeStatement/GetCSInfoDetails",
  "/ComparativeStatement/CreateOrUpdateCostComponentTransaction",
  "/ComparativeStatement/GetByCostComponentPartner",
];
