import axios from 'axios';
import { toast } from 'react-toastify';

// get selected business unit from store

export const getPurchaseReqGridData = async (
   activityId,
   accId,
   buId,
   userId,
   setter,
   setLoading,
   pageNo,
   pageSize,
   search,
   plantId
) => {
   const Search = search ? `&Search=${search}` : '';

   try {
      setLoading(true);
      const res = await axios.get(
         // `/procurement/Approval/GetPurchaseRequestApprovalList?BusinessUnitId=${buId}&UserId=${userId}&viewOrder=desc&PageNo=${pageNo}&PageSize=${pageSize}`
         `/procurement/Approval/CoomonApprovalList?AcountId=${accId}&BusinessUnitId=${buId}&UserId=${userId}&ActivityId=${activityId}&viewOrder=desc&PageNo=${pageNo ||
            1}&PageSize=${pageSize}${Search}&plantId=${plantId}`
      );
      if (res.status === 200 && res?.data) {
         setter({
            data: res?.data?.map(itm => ({
               ...itm,
               isSelect: false,
            })),
            totalCount: res?.data[0]?.totalRows,
            currentPage: res?.data?.currentPage,
            pageSize: res?.data?.pageSize,
         });
         // console.log(res.data)
         // setter(res?.data);
         setLoading(false);
      }
   } catch (error) {
      setter([]);
      setLoading(false);
   }
};

export const approvalApi = async (
   parameter,
   poayload,
   activityName,
   onChangeForActivity,
   setBillSubmitBtn
) => {
   try {
      await axios.put(
         `/procurement/Approval/CommonApproved?AcountId=${parameter?.accid}&BusinessUnitId=${parameter?.buId}&UserId=${parameter?.userId}&ActivityId=${parameter?.activityId}`,
         poayload
      );
      toast.success('Approved successfully');
      setBillSubmitBtn(true);
      onChangeForActivity();
   } catch (error) {
      toast.error(error?.response?.data?.message || 'Approval Failed');
   }
};

export const dummyDataForCSDetails = {
   objHeder: {
      sl: null,
      intRequestForQuotationId: 434,
      strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
      dteRfqdate: '2024-04-13T00:00:00',
      intAccountId: 1,
      strAccountName: 'Akij Resource Limited',
      intBusinessUnitId: 102,
      strBusinessUnitName: 'AKIJ SHIPPING LINES PTE LTD, SINGAPORE',
      intSbuid: 80,
      strSbuname: 'AKIJ SHIPPING LINES PTE LTD, SINGAPORE',
      intPurchaseOrganizationId: 11,
      strPurchaseOrganizationName: 'Local Procurement',
      intPlantId: 97,
      strPlantName: 'MV Akij Wave',
      intWarehouseId: 10307,
      strWarehouseName: 'MV Akij Wave(WH-PTE-Deck)',
      intRfqTypeId: 1,
      strRfqTypeName: 'Standard RFQ',
      intRequestTypeId: 1,
      strRequestTypeName: 'Request for quotation',
      strReferenceTypeName: 'With Reference',
      intCurrencyId: 141,
      strCurrencyCode: 'BDT',
      dteValidTillDate: null,
      isApproved: false,
      intApprovedBy: -1,
      strApprovedBy: '',
      dteApprovedDateTime: '2024-04-13T10:39:07.967',
      intActionBy: 377857,
      dteLastActionDateTime: '2024-04-15T10:33:14.703',
      dteServerDateTime: '2024-04-13T10:39:07.967',
      isActive: true,
      strDeliveryAddress: 'CTG O/A',
      strVatAti: '',
      strTransportCost: '',
      quotationStartDateTime: '2024-04-13T16:37:00',
      quotationEndDateTime: '2024-04-15T10:33:14.703',
      termsAndConditions: '',
      intPaymentTermsId: 0,
      strPaymentTermsName: '',
      strAttachment: '',
      strStatus: null,
   },
   objRow: [
      {
         intRowId: 13186,
         intRequestForQuotationId: 0,
         strRequestForQuotationCode: null,
         strPrreferenceCode: null,
         intItemId: 106964,
         strItemCode: '0',
         strItemName: 'MINERAL WATER SPA (6 BTL x 2.25 LTR) / CASE',
         strItemTypeName: 'Maintenance Repair and Operating Supplies',
         intUoMid: 148,
         strUoMname: 'CASE',
         numRfqquantity: 50,
         intReferenceId: null,
         strReferenceCode: null,
         numReferenceQuantity: 50,
         strDescription: '',
         isActive: false,
         numRestQuantity: null,
         intItemCategoryId: 588,
         strPartNo: '',
         strDrawingNo: '',
         objPartnerHeader: [
            {
               intPartnerRfqid: 1572,
               intRequestForQuotationId: 434,
               strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
               intAccountId: 1,
               intBusinessUnitId: 102,
               intBusinessPartnerId: 75546,
               strBusinessPartnerName: 'M/S. Sofiqe & Brothers [21118713]',
               strBusinessPartnerCode: '',
               strBusinessPartnerAddress:
                  '52 Jublee Road, Riazudding Bazar, Chittagong BA:0002233001335 RN:070157512 BN:BANK ASIA LTD BBrN:STATION ROAD',
               strSupplierRefNo: 'SB/AWV/0057/2023',
               dteSupplierRefDate: '2024-04-15T00:00:00',
               strEmail: 'sofique.bros@gmail.com',
               strContactNumber: '01714318848',
               dteIssueDate: '2024-04-13T00:00:00',
               dteReleaseDate: '2024-04-13T00:00:00',
               strDocAttachmentLink: '',
               isQuotationReceived: false,
               isEmailSend: false,
               intLastActionBy: 377857,
               dteLastActionDateTime: '2024-04-13T10:39:07.987',
               dteServerDateTime: '2024-04-13T10:39:07.987',
               isActive: true,
               isQuotation: true,
               objPartnerRow: {
                  intRowId: 0,
                  intPartnerRfqid: 1572,
                  strPrreferenceCode: null,
                  intItemId: 106964,
                  strItemCode: null,
                  strItemName: null,
                  strItemTypeName: null,
                  intUoMid: 0,
                  strUoMname: null,
                  numRequestQuantity: null,
                  numRate: 220,
                  numValue: 11000,
                  isSelected: false,
                  strSelectionComments: null,
                  strRemarks: null,
                  intActionBy: null,
                  dteLastActionDateTime: null,
                  dteServerDateTime: null,
                  isActive: false,
                  numNegotiationRate: 0,
                  strNegotiationRemarks: null,
                  numTotalvalue: 11000,
                  strAttachment: null,
               },
            },
            {
               intPartnerRfqid: 1573,
               intRequestForQuotationId: 434,
               strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
               intAccountId: 1,
               intBusinessUnitId: 102,
               intBusinessPartnerId: 75601,
               strBusinessPartnerName: 'M/S. Fazal Traders [21118768]',
               strBusinessPartnerCode: '',
               strBusinessPartnerAddress:
                  '53,Rahamantunnessa Road, Raazuddin Bazar, Chittagong BA:0791330003018 RN:195157163 BN:SOCIAL ISLAMI BANK LTD BBrN:SHAH MOHSIN AWLIA',
               strSupplierRefNo: '',
               dteSupplierRefDate: '2024-04-13T10:39:08.007',
               strEmail: 'fazaltradersbd12@gmail.com',
               strContactNumber: '01812836732',
               dteIssueDate: '2024-04-13T00:00:00',
               dteReleaseDate: '2024-04-13T00:00:00',
               strDocAttachmentLink: '',
               isQuotationReceived: false,
               isEmailSend: false,
               intLastActionBy: 377857,
               dteLastActionDateTime: '2024-04-13T10:39:08.007',
               dteServerDateTime: '2024-04-13T10:39:08.007',
               isActive: true,
               isQuotation: null,
               objPartnerRow: {
                  intRowId: 0,
                  intPartnerRfqid: 1573,
                  strPrreferenceCode: null,
                  intItemId: 106964,
                  strItemCode: null,
                  strItemName: null,
                  strItemTypeName: null,
                  intUoMid: 0,
                  strUoMname: null,
                  numRequestQuantity: null,
                  numRate: 0,
                  numValue: 0,
                  isSelected: false,
                  strSelectionComments: null,
                  strRemarks: '',
                  intActionBy: null,
                  dteLastActionDateTime: null,
                  dteServerDateTime: null,
                  isActive: false,
                  numNegotiationRate: 0,
                  strNegotiationRemarks: null,
                  numTotalvalue: 0,
                  strAttachment: null,
               },
            },
            {
               intPartnerRfqid: 1574,
               intRequestForQuotationId: 434,
               strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
               intAccountId: 1,
               intBusinessUnitId: 102,
               intBusinessPartnerId: 75673,
               strBusinessPartnerName: 'New M/S Fazal Traders [21118840]',
               strBusinessPartnerCode: '',
               strBusinessPartnerAddress:
                  '301 Kabir Market, Asad Gonj, Kotwali, Chittagong-4000, Bangladesh BA:0581020004715 RN:165151849 BN:ONE BANK LTD BBrN:CHANDGAON',
               strSupplierRefNo: '',
               dteSupplierRefDate: '2024-04-13T10:39:08.02',
               strEmail: 'Fazaltraders2012@Yahoo.Com',
               strContactNumber: '01712836607',
               dteIssueDate: '2024-04-13T00:00:00',
               dteReleaseDate: '2024-04-13T00:00:00',
               strDocAttachmentLink: '',
               isQuotationReceived: false,
               isEmailSend: false,
               intLastActionBy: 377857,
               dteLastActionDateTime: '2024-04-13T10:39:08.02',
               dteServerDateTime: '2024-04-13T10:39:08.02',
               isActive: true,
               isQuotation: null,
               objPartnerRow: {
                  intRowId: 0,
                  intPartnerRfqid: 1574,
                  strPrreferenceCode: null,
                  intItemId: 106964,
                  strItemCode: null,
                  strItemName: null,
                  strItemTypeName: null,
                  intUoMid: 0,
                  strUoMname: null,
                  numRequestQuantity: null,
                  numRate: 0,
                  numValue: 0,
                  isSelected: false,
                  strSelectionComments: null,
                  strRemarks: '',
                  intActionBy: null,
                  dteLastActionDateTime: null,
                  dteServerDateTime: null,
                  isActive: false,
                  numNegotiationRate: 0,
                  strNegotiationRemarks: null,
                  numTotalvalue: 0,
                  strAttachment: null,
               },
            },
            {
               intPartnerRfqid: 1575,
               intRequestForQuotationId: 434,
               strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
               intAccountId: 1,
               intBusinessUnitId: 102,
               intBusinessPartnerId: 75562,
               strBusinessPartnerName: 'M/S Hossain Enterprise [21118729]',
               strBusinessPartnerCode: '',
               strBusinessPartnerAddress:
                  '61 No, Rahmatennessa Road, Reajuddin Bazar Ctg. BA:0181020015638 RN:015153647 BN:AL-ARAFAH ISLAMI BANK LTD BBrN:JUBILEE ROAD',
               strSupplierRefNo: 'M/S hossain/akij-wave/Bond',
               dteSupplierRefDate: '2024-04-15T00:00:00',
               strEmail: 'hossainahmed4072@gmail.com',
               strContactNumber: '01825124072',
               dteIssueDate: '2024-04-13T00:00:00',
               dteReleaseDate: '2024-04-13T00:00:00',
               strDocAttachmentLink: '',
               isQuotationReceived: false,
               isEmailSend: false,
               intLastActionBy: 377857,
               dteLastActionDateTime: '2024-04-13T10:39:08.057',
               dteServerDateTime: '2024-04-13T10:39:08.057',
               isActive: true,
               isQuotation: true,
               objPartnerRow: {
                  intRowId: 0,
                  intPartnerRfqid: 1575,
                  strPrreferenceCode: null,
                  intItemId: 106964,
                  strItemCode: null,
                  strItemName: null,
                  strItemTypeName: null,
                  intUoMid: 0,
                  strUoMname: null,
                  numRequestQuantity: null,
                  numRate: 250,
                  numValue: 12500,
                  isSelected: false,
                  strSelectionComments: null,
                  strRemarks: null,
                  intActionBy: null,
                  dteLastActionDateTime: null,
                  dteServerDateTime: null,
                  isActive: false,
                  numNegotiationRate: 0,
                  strNegotiationRemarks: null,
                  numTotalvalue: 12500,
                  strAttachment: null,
               },
            },
         ],
      },
      {
         intRowId: 13187,
         intRequestForQuotationId: 0,
         strRequestForQuotationCode: null,
         strPrreferenceCode: null,
         intItemId: 107953,
         strItemCode: '0',
         strItemName: 'SOFT DRINKS FANTA (330ML x 24 CAN) CASE',
         strItemTypeName: 'Maintenance Repair and Operating Supplies',
         intUoMid: 148,
         strUoMname: 'CASE',
         numRfqquantity: 5,
         intReferenceId: null,
         strReferenceCode: null,
         numReferenceQuantity: 5,
         strDescription: '',
         isActive: false,
         numRestQuantity: null,
         intItemCategoryId: 588,
         strPartNo: '',
         strDrawingNo: '',
         objPartnerHeader: [
            {
               intPartnerRfqid: 1572,
               intRequestForQuotationId: 434,
               strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
               intAccountId: 1,
               intBusinessUnitId: 102,
               intBusinessPartnerId: 75546,
               strBusinessPartnerName: 'M/S. Sofiqe & Brothers [21118713]',
               strBusinessPartnerCode: '',
               strBusinessPartnerAddress:
                  '52 Jublee Road, Riazudding Bazar, Chittagong BA:0002233001335 RN:070157512 BN:BANK ASIA LTD BBrN:STATION ROAD',
               strSupplierRefNo: 'SB/AWV/0057/2023',
               dteSupplierRefDate: '2024-04-15T00:00:00',
               strEmail: 'sofique.bros@gmail.com',
               strContactNumber: '01714318848',
               dteIssueDate: '2024-04-13T00:00:00',
               dteReleaseDate: '2024-04-13T00:00:00',
               strDocAttachmentLink: '',
               isQuotationReceived: false,
               isEmailSend: false,
               intLastActionBy: 377857,
               dteLastActionDateTime: '2024-04-13T10:39:07.987',
               dteServerDateTime: '2024-04-13T10:39:07.987',
               isActive: true,
               isQuotation: true,
               objPartnerRow: {
                  intRowId: 0,
                  intPartnerRfqid: 1572,
                  strPrreferenceCode: null,
                  intItemId: 107953,
                  strItemCode: null,
                  strItemName: null,
                  strItemTypeName: null,
                  intUoMid: 0,
                  strUoMname: null,
                  numRequestQuantity: null,
                  numRate: 850,
                  numValue: 4250,
                  isSelected: false,
                  strSelectionComments: null,
                  strRemarks: null,
                  intActionBy: null,
                  dteLastActionDateTime: null,
                  dteServerDateTime: null,
                  isActive: false,
                  numNegotiationRate: 0,
                  strNegotiationRemarks: null,
                  numTotalvalue: 4250,
                  strAttachment: null,
               },
            },
            {
               intPartnerRfqid: 1573,
               intRequestForQuotationId: 434,
               strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
               intAccountId: 1,
               intBusinessUnitId: 102,
               intBusinessPartnerId: 75601,
               strBusinessPartnerName: 'M/S. Fazal Traders [21118768]',
               strBusinessPartnerCode: '',
               strBusinessPartnerAddress:
                  '53,Rahamantunnessa Road, Raazuddin Bazar, Chittagong BA:0791330003018 RN:195157163 BN:SOCIAL ISLAMI BANK LTD BBrN:SHAH MOHSIN AWLIA',
               strSupplierRefNo: '',
               dteSupplierRefDate: '2024-04-13T10:39:08.007',
               strEmail: 'fazaltradersbd12@gmail.com',
               strContactNumber: '01812836732',
               dteIssueDate: '2024-04-13T00:00:00',
               dteReleaseDate: '2024-04-13T00:00:00',
               strDocAttachmentLink: '',
               isQuotationReceived: false,
               isEmailSend: false,
               intLastActionBy: 377857,
               dteLastActionDateTime: '2024-04-13T10:39:08.007',
               dteServerDateTime: '2024-04-13T10:39:08.007',
               isActive: true,
               isQuotation: null,
               objPartnerRow: {
                  intRowId: 0,
                  intPartnerRfqid: 1573,
                  strPrreferenceCode: null,
                  intItemId: 107953,
                  strItemCode: null,
                  strItemName: null,
                  strItemTypeName: null,
                  intUoMid: 0,
                  strUoMname: null,
                  numRequestQuantity: null,
                  numRate: 0,
                  numValue: 0,
                  isSelected: false,
                  strSelectionComments: null,
                  strRemarks: '',
                  intActionBy: null,
                  dteLastActionDateTime: null,
                  dteServerDateTime: null,
                  isActive: false,
                  numNegotiationRate: 0,
                  strNegotiationRemarks: null,
                  numTotalvalue: 0,
                  strAttachment: null,
               },
            },
            {
               intPartnerRfqid: 1574,
               intRequestForQuotationId: 434,
               strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
               intAccountId: 1,
               intBusinessUnitId: 102,
               intBusinessPartnerId: 75673,
               strBusinessPartnerName: 'New M/S Fazal Traders [21118840]',
               strBusinessPartnerCode: '',
               strBusinessPartnerAddress:
                  '301 Kabir Market, Asad Gonj, Kotwali, Chittagong-4000, Bangladesh BA:0581020004715 RN:165151849 BN:ONE BANK LTD BBrN:CHANDGAON',
               strSupplierRefNo: '',
               dteSupplierRefDate: '2024-04-13T10:39:08.02',
               strEmail: 'Fazaltraders2012@Yahoo.Com',
               strContactNumber: '01712836607',
               dteIssueDate: '2024-04-13T00:00:00',
               dteReleaseDate: '2024-04-13T00:00:00',
               strDocAttachmentLink: '',
               isQuotationReceived: false,
               isEmailSend: false,
               intLastActionBy: 377857,
               dteLastActionDateTime: '2024-04-13T10:39:08.02',
               dteServerDateTime: '2024-04-13T10:39:08.02',
               isActive: true,
               isQuotation: null,
               objPartnerRow: {
                  intRowId: 0,
                  intPartnerRfqid: 1574,
                  strPrreferenceCode: null,
                  intItemId: 107953,
                  strItemCode: null,
                  strItemName: null,
                  strItemTypeName: null,
                  intUoMid: 0,
                  strUoMname: null,
                  numRequestQuantity: null,
                  numRate: 0,
                  numValue: 0,
                  isSelected: false,
                  strSelectionComments: null,
                  strRemarks: '',
                  intActionBy: null,
                  dteLastActionDateTime: null,
                  dteServerDateTime: null,
                  isActive: false,
                  numNegotiationRate: 0,
                  strNegotiationRemarks: null,
                  numTotalvalue: 0,
                  strAttachment: null,
               },
            },
            {
               intPartnerRfqid: 1575,
               intRequestForQuotationId: 434,
               strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
               intAccountId: 1,
               intBusinessUnitId: 102,
               intBusinessPartnerId: 75562,
               strBusinessPartnerName: 'M/S Hossain Enterprise [21118729]',
               strBusinessPartnerCode: '',
               strBusinessPartnerAddress:
                  '61 No, Rahmatennessa Road, Reajuddin Bazar Ctg. BA:0181020015638 RN:015153647 BN:AL-ARAFAH ISLAMI BANK LTD BBrN:JUBILEE ROAD',
               strSupplierRefNo: 'M/S hossain/akij-wave/Bond',
               dteSupplierRefDate: '2024-04-15T00:00:00',
               strEmail: 'hossainahmed4072@gmail.com',
               strContactNumber: '01825124072',
               dteIssueDate: '2024-04-13T00:00:00',
               dteReleaseDate: '2024-04-13T00:00:00',
               strDocAttachmentLink: '',
               isQuotationReceived: false,
               isEmailSend: false,
               intLastActionBy: 377857,
               dteLastActionDateTime: '2024-04-13T10:39:08.057',
               dteServerDateTime: '2024-04-13T10:39:08.057',
               isActive: true,
               isQuotation: true,
               objPartnerRow: {
                  intRowId: 0,
                  intPartnerRfqid: 1575,
                  strPrreferenceCode: null,
                  intItemId: 107953,
                  strItemCode: null,
                  strItemName: null,
                  strItemTypeName: null,
                  intUoMid: 0,
                  strUoMname: null,
                  numRequestQuantity: null,
                  numRate: 1750,
                  numValue: 8750,
                  isSelected: false,
                  strSelectionComments: null,
                  strRemarks: null,
                  intActionBy: null,
                  dteLastActionDateTime: null,
                  dteServerDateTime: null,
                  isActive: false,
                  numNegotiationRate: 0,
                  strNegotiationRemarks: null,
                  numTotalvalue: 8750,
                  strAttachment: null,
               },
            },
         ],
      },
      {
         intRowId: 13188,
         intRequestForQuotationId: 0,
         strRequestForQuotationCode: null,
         strPrreferenceCode: null,
         intItemId: 169548,
         strItemCode: '0',
         strItemName: 'MINERAL WATER SPA (24 BTL x 500 ml) / CASE',
         strItemTypeName: 'Maintenance Repair and Operating Supplies',
         intUoMid: 166,
         strUoMname: 'CASE',
         numRfqquantity: 2,
         intReferenceId: null,
         strReferenceCode: null,
         numReferenceQuantity: 2,
         strDescription: '',
         isActive: false,
         numRestQuantity: null,
         intItemCategoryId: 588,
         strPartNo: '',
         strDrawingNo: '',
         objPartnerHeader: [
            {
               intPartnerRfqid: 1572,
               intRequestForQuotationId: 434,
               strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
               intAccountId: 1,
               intBusinessUnitId: 102,
               intBusinessPartnerId: 75546,
               strBusinessPartnerName: 'M/S. Sofiqe & Brothers [21118713]',
               strBusinessPartnerCode: '',
               strBusinessPartnerAddress:
                  '52 Jublee Road, Riazudding Bazar, Chittagong BA:0002233001335 RN:070157512 BN:BANK ASIA LTD BBrN:STATION ROAD',
               strSupplierRefNo: 'SB/AWV/0057/2023',
               dteSupplierRefDate: '2024-04-15T00:00:00',
               strEmail: 'sofique.bros@gmail.com',
               strContactNumber: '01714318848',
               dteIssueDate: '2024-04-13T00:00:00',
               dteReleaseDate: '2024-04-13T00:00:00',
               strDocAttachmentLink: '',
               isQuotationReceived: false,
               isEmailSend: false,
               intLastActionBy: 377857,
               dteLastActionDateTime: '2024-04-13T10:39:07.987',
               dteServerDateTime: '2024-04-13T10:39:07.987',
               isActive: true,
               isQuotation: true,
               objPartnerRow: {
                  intRowId: 0,
                  intPartnerRfqid: 1572,
                  strPrreferenceCode: null,
                  intItemId: 169548,
                  strItemCode: null,
                  strItemName: null,
                  strItemTypeName: null,
                  intUoMid: 0,
                  strUoMname: null,
                  numRequestQuantity: null,
                  numRate: 300,
                  numValue: 600,
                  isSelected: false,
                  strSelectionComments: null,
                  strRemarks: null,
                  intActionBy: null,
                  dteLastActionDateTime: null,
                  dteServerDateTime: null,
                  isActive: false,
                  numNegotiationRate: 0,
                  strNegotiationRemarks: null,
                  numTotalvalue: 600,
                  strAttachment: null,
               },
            },
            {
               intPartnerRfqid: 1573,
               intRequestForQuotationId: 434,
               strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
               intAccountId: 1,
               intBusinessUnitId: 102,
               intBusinessPartnerId: 75601,
               strBusinessPartnerName: 'M/S. Fazal Traders [21118768]',
               strBusinessPartnerCode: '',
               strBusinessPartnerAddress:
                  '53,Rahamantunnessa Road, Raazuddin Bazar, Chittagong BA:0791330003018 RN:195157163 BN:SOCIAL ISLAMI BANK LTD BBrN:SHAH MOHSIN AWLIA',
               strSupplierRefNo: '',
               dteSupplierRefDate: '2024-04-13T10:39:08.007',
               strEmail: 'fazaltradersbd12@gmail.com',
               strContactNumber: '01812836732',
               dteIssueDate: '2024-04-13T00:00:00',
               dteReleaseDate: '2024-04-13T00:00:00',
               strDocAttachmentLink: '',
               isQuotationReceived: false,
               isEmailSend: false,
               intLastActionBy: 377857,
               dteLastActionDateTime: '2024-04-13T10:39:08.007',
               dteServerDateTime: '2024-04-13T10:39:08.007',
               isActive: true,
               isQuotation: null,
               objPartnerRow: {
                  intRowId: 0,
                  intPartnerRfqid: 1573,
                  strPrreferenceCode: null,
                  intItemId: 169548,
                  strItemCode: null,
                  strItemName: null,
                  strItemTypeName: null,
                  intUoMid: 0,
                  strUoMname: null,
                  numRequestQuantity: null,
                  numRate: 0,
                  numValue: 0,
                  isSelected: false,
                  strSelectionComments: null,
                  strRemarks: '',
                  intActionBy: null,
                  dteLastActionDateTime: null,
                  dteServerDateTime: null,
                  isActive: false,
                  numNegotiationRate: 0,
                  strNegotiationRemarks: null,
                  numTotalvalue: 0,
                  strAttachment: null,
               },
            },
            {
               intPartnerRfqid: 1574,
               intRequestForQuotationId: 434,
               strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
               intAccountId: 1,
               intBusinessUnitId: 102,
               intBusinessPartnerId: 75673,
               strBusinessPartnerName: 'New M/S Fazal Traders [21118840]',
               strBusinessPartnerCode: '',
               strBusinessPartnerAddress:
                  '301 Kabir Market, Asad Gonj, Kotwali, Chittagong-4000, Bangladesh BA:0581020004715 RN:165151849 BN:ONE BANK LTD BBrN:CHANDGAON',
               strSupplierRefNo: '',
               dteSupplierRefDate: '2024-04-13T10:39:08.02',
               strEmail: 'Fazaltraders2012@Yahoo.Com',
               strContactNumber: '01712836607',
               dteIssueDate: '2024-04-13T00:00:00',
               dteReleaseDate: '2024-04-13T00:00:00',
               strDocAttachmentLink: '',
               isQuotationReceived: false,
               isEmailSend: false,
               intLastActionBy: 377857,
               dteLastActionDateTime: '2024-04-13T10:39:08.02',
               dteServerDateTime: '2024-04-13T10:39:08.02',
               isActive: true,
               isQuotation: null,
               objPartnerRow: {
                  intRowId: 0,
                  intPartnerRfqid: 1574,
                  strPrreferenceCode: null,
                  intItemId: 169548,
                  strItemCode: null,
                  strItemName: null,
                  strItemTypeName: null,
                  intUoMid: 0,
                  strUoMname: null,
                  numRequestQuantity: null,
                  numRate: 0,
                  numValue: 0,
                  isSelected: false,
                  strSelectionComments: null,
                  strRemarks: '',
                  intActionBy: null,
                  dteLastActionDateTime: null,
                  dteServerDateTime: null,
                  isActive: false,
                  numNegotiationRate: 0,
                  strNegotiationRemarks: null,
                  numTotalvalue: 0,
                  strAttachment: null,
               },
            },
            {
               intPartnerRfqid: 1575,
               intRequestForQuotationId: 434,
               strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
               intAccountId: 1,
               intBusinessUnitId: 102,
               intBusinessPartnerId: 75562,
               strBusinessPartnerName: 'M/S Hossain Enterprise [21118729]',
               strBusinessPartnerCode: '',
               strBusinessPartnerAddress:
                  '61 No, Rahmatennessa Road, Reajuddin Bazar Ctg. BA:0181020015638 RN:015153647 BN:AL-ARAFAH ISLAMI BANK LTD BBrN:JUBILEE ROAD',
               strSupplierRefNo: 'M/S hossain/akij-wave/Bond',
               dteSupplierRefDate: '2024-04-15T00:00:00',
               strEmail: 'hossainahmed4072@gmail.com',
               strContactNumber: '01825124072',
               dteIssueDate: '2024-04-13T00:00:00',
               dteReleaseDate: '2024-04-13T00:00:00',
               strDocAttachmentLink: '',
               isQuotationReceived: false,
               isEmailSend: false,
               intLastActionBy: 377857,
               dteLastActionDateTime: '2024-04-13T10:39:08.057',
               dteServerDateTime: '2024-04-13T10:39:08.057',
               isActive: true,
               isQuotation: true,
               objPartnerRow: {
                  intRowId: 0,
                  intPartnerRfqid: 1575,
                  strPrreferenceCode: null,
                  intItemId: 169548,
                  strItemCode: null,
                  strItemName: null,
                  strItemTypeName: null,
                  intUoMid: 0,
                  strUoMname: null,
                  numRequestQuantity: null,
                  numRate: 500,
                  numValue: 1000,
                  isSelected: false,
                  strSelectionComments: null,
                  strRemarks: null,
                  intActionBy: null,
                  dteLastActionDateTime: null,
                  dteServerDateTime: null,
                  isActive: false,
                  numNegotiationRate: 0,
                  strNegotiationRemarks: null,
                  numTotalvalue: 1000,
                  strAttachment: null,
               },
            },
         ],
      },
   ],
   objPartnerHead: [
      {
         intPartnerRfqid: 1572,
         intRequestForQuotationId: 434,
         strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
         intAccountId: 1,
         intBusinessUnitId: 102,
         intBusinessPartnerId: 75546,
         strBusinessPartnerName: 'M/S. Sofiqe & Brothers [21118713]',
         strBusinessPartnerCode: '',
         strBusinessPartnerAddress:
            '52 Jublee Road, Riazudding Bazar, Chittagong BA:0002233001335 RN:070157512 BN:BANK ASIA LTD BBrN:STATION ROAD',
         strSupplierRefNo: 'SB/AWV/0057/2023',
         dteSupplierRefDate: '2024-04-15T00:00:00',
         strEmail: 'sofique.bros@gmail.com',
         strContactNumber: '01714318848',
         dteIssueDate: '2024-04-13T00:00:00',
         dteReleaseDate: '2024-04-13T00:00:00',
         strDocAttachmentLink: '',
         isQuotationReceived: false,
         isEmailSend: false,
         intLastActionBy: 377857,
         dteLastActionDateTime: '2024-04-13T10:39:07.987',
         dteServerDateTime: '2024-04-13T10:39:07.987',
         strRemarks: '',
         isActive: true,
         isQuotation: true,
         totalOfferedValue: 15850,
         totalNegotiatedValue: 15850,
         sumValue: 15850,
         numTransportCost: 0,
         numOthersCost: 0,
         numDiscountPercentage: 0,
      },
      {
         intPartnerRfqid: 1573,
         intRequestForQuotationId: 434,
         strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
         intAccountId: 1,
         intBusinessUnitId: 102,
         intBusinessPartnerId: 75601,
         strBusinessPartnerName: 'M/S. Fazal Traders [21118768]',
         strBusinessPartnerCode: '',
         strBusinessPartnerAddress:
            '53,Rahamantunnessa Road, Raazuddin Bazar, Chittagong BA:0791330003018 RN:195157163 BN:SOCIAL ISLAMI BANK LTD BBrN:SHAH MOHSIN AWLIA',
         strSupplierRefNo: '',
         dteSupplierRefDate: '2024-04-13T10:39:08.007',
         strEmail: 'fazaltradersbd12@gmail.com',
         strContactNumber: '01812836732',
         dteIssueDate: '2024-04-13T00:00:00',
         dteReleaseDate: '2024-04-13T00:00:00',
         strDocAttachmentLink: '',
         isQuotationReceived: false,
         isEmailSend: false,
         intLastActionBy: 377857,
         dteLastActionDateTime: '2024-04-13T10:39:08.007',
         dteServerDateTime: '2024-04-13T10:39:08.007',
         strRemarks: null,
         isActive: true,
         isQuotation: null,
         totalOfferedValue: 0,
         totalNegotiatedValue: 0,
         sumValue: 0,
         numTransportCost: 0,
         numOthersCost: 0,
         numDiscountPercentage: 0,
      },
      {
         intPartnerRfqid: 1574,
         intRequestForQuotationId: 434,
         strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
         intAccountId: 1,
         intBusinessUnitId: 102,
         intBusinessPartnerId: 75673,
         strBusinessPartnerName: 'New M/S Fazal Traders [21118840]',
         strBusinessPartnerCode: '',
         strBusinessPartnerAddress:
            '301 Kabir Market, Asad Gonj, Kotwali, Chittagong-4000, Bangladesh BA:0581020004715 RN:165151849 BN:ONE BANK LTD BBrN:CHANDGAON',
         strSupplierRefNo: '',
         dteSupplierRefDate: '2024-04-13T10:39:08.02',
         strEmail: 'Fazaltraders2012@Yahoo.Com',
         strContactNumber: '01712836607',
         dteIssueDate: '2024-04-13T00:00:00',
         dteReleaseDate: '2024-04-13T00:00:00',
         strDocAttachmentLink: '',
         isQuotationReceived: false,
         isEmailSend: false,
         intLastActionBy: 377857,
         dteLastActionDateTime: '2024-04-13T10:39:08.02',
         dteServerDateTime: '2024-04-13T10:39:08.02',
         strRemarks: null,
         isActive: true,
         isQuotation: null,
         totalOfferedValue: 0,
         totalNegotiatedValue: 0,
         sumValue: 0,
         numTransportCost: 0,
         numOthersCost: 0,
         numDiscountPercentage: 0,
      },
      {
         intPartnerRfqid: 1575,
         intRequestForQuotationId: 434,
         strRequestForQuotationCode: 'RFQ-AWV/DK/BO-00189-1',
         intAccountId: 1,
         intBusinessUnitId: 102,
         intBusinessPartnerId: 75562,
         strBusinessPartnerName: 'M/S Hossain Enterprise [21118729]',
         strBusinessPartnerCode: '',
         strBusinessPartnerAddress:
            '61 No, Rahmatennessa Road, Reajuddin Bazar Ctg. BA:0181020015638 RN:015153647 BN:AL-ARAFAH ISLAMI BANK LTD BBrN:JUBILEE ROAD',
         strSupplierRefNo: 'M/S hossain/akij-wave/Bond',
         dteSupplierRefDate: '2024-04-15T00:00:00',
         strEmail: 'hossainahmed4072@gmail.com',
         strContactNumber: '01825124072',
         dteIssueDate: '2024-04-13T00:00:00',
         dteReleaseDate: '2024-04-13T00:00:00',
         strDocAttachmentLink: '',
         isQuotationReceived: false,
         isEmailSend: false,
         intLastActionBy: 377857,
         dteLastActionDateTime: '2024-04-13T10:39:08.057',
         dteServerDateTime: '2024-04-13T10:39:08.057',
         strRemarks: '',
         isActive: true,
         isQuotation: true,
         totalOfferedValue: 22250,
         totalNegotiatedValue: 22250,
         sumValue: 22250,
         numTransportCost: 0,
         numOthersCost: 0,
         numDiscountPercentage: 0,
      },
   ],
};
